version: "2"

services:
  backend:
    build: .
    ports:
      - 3333:3333
      - 8000:8000
      - 9229:9229 # DEBUG PORT
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    environment:
      PORT: 3333
